spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql:Your BDD url.
    username: ""
    password: ""
  jpa:
    hibernate:
      ddl-auto: update

trabaho:
  app:
    jwtSecret: ""
    jwtExpirationMs: ""
